#!/usr/bin/env Rscript

cat("remainder: 7 %% 3 ==",7%%3,"\n")
cat("quotient: 7 %/% 3 ==",7%/%3,"\n")
cat("exponential: 7 ^ 3 ==",7^3,"\n")
cat("Same with vectors:\n")
a <- c(1.5,5,11)
b <- c(2,2,3)
c <- c(0,5,10)
d <- c(0,15,100)
cat("a:",a,"\n")
cat("b:",b,"\n")
cat("a%%b:",a%%b,"\n")
cat("a%/%b:",a%/%b,"\n")
cat("a^b:",a^b,"\n")
cat("\n")

cat("& element-wise logical AND:\n")
cat("1 & 2 ==",1&2,"\n")
cat("1 & 0 ==",1&0,"\n")
cat("TRUE & FALSE ==",T&F,"\n")
cat("1 & NA ==",1&NA,"\n")
cat("1 & NULL ==",1&NULL,"(logical(0))\n")
cat("\n")

cat("| element-wise logical OR:\n")
cat("1 | 2 ==",1|2,"\n")
cat("1 | 0 ==",1|0,"\n")
cat("0 | 0 ==",0|0,"\n")
cat("TRUE | FALSE ==",T|F,"\n")
cat("1 | NA ==",1|NA,"\n")
cat("1 | NULL ==",1|NULL,"(logical(0))\n")
cat("\n")

cat("! logical NOT\n")
cat("!1 ==",!1,"\n")
cat("!0 ==",!0,"\n")
cat("!TRUE ==",!T,"\n")
cat("!FALSE ==",!F,"\n")
cat("!NA ==",!NA,"\n")
cat("\n")

cat("&& takes first element only:\n")
cat("a & b",a&b,"\n")
cat("a && b",a&&b,"\n")
cat("c:",c,"\n")
cat("a & c",a&c,"\n")
cat("a && c",a&&c,"\n")
cat("c(TRUE,FALSE) && c(TRUE,FALSE) ==",c(T,F)&&c(T,F),"\n")
cat("\n")

cat("|| takes first element only:\n")
cat("a | c",a|c,"\n")
cat("a || c",a||c,"\n")
cat("d:",d,"\n")
cat("c | d",c|d,"\n")
cat("c || d",c||d,"\n")
cat("c(TRUE,FALSE) || c(FALSE,FALSE) ==",c(T,F)||c(F,F),"\n")
cat("\n")

cat("n:m for a sequence of numbers:\n")
cat("1:10 ==",1:10,"\n")
cat("%in% whether element a is in vector c\n")
cat("3 %in% 1:10 ==",3 %in% 1:10,"\n")
cat("11 %in% 1:10 ==",11 %in% 1:10,"\n")

m <- matrix(1:9,nrow=3,byrow=T)
cat("a matrix: m\n")
print(m)
cat("m %*% m: multiply matrices\n")
print(m%*%m)
cat("a transpose of m\n")
print(t(m))
cat("m %*% t(m): m and t(m) multiplied:\n")
print(m %*% t(m))
